In [20]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [21]:
df = pd.read_excel(r"C:\Users\dell\Downloads\bakery_synthetic_dataset.csv (1).xlsx")
df.head(20)

,Transaction_ID,Date,Time,Customer_ID,Customer_Age,Customer_Gender,Product,Category,Quantity,Unit_Price,...,Promotion_Applied,Promotion_Type,Promotion_Score,Customer_Rating,Customer_Segment,Loyalty_Member,Profit,Waste_Cost,Recommended_Product,Recommended_Discount
0,TXN000038,2023-01-01,07:13:00,CUST01289,32,Male,Rusk,Biscuits & Cookies,1,34.79,...,Yes,Festival,100,4,Young Professional,Yes,-4.28,7.71,Rusk,13.0
1,TXN000039,2023-01-01,07:13:00,CUST01289,32,Male,Peanut Butter,Spreads,4,176.62,...,Yes,Festival,100,4,Young Professional,Yes,-105.15,171.43,Bread,9.0
2,TXN000040,2023-01-01,07:13:00,CUST01289,32,Male,Black Forest Cake,Cakes,2,448.03,...,Yes,Festival,100,4,Young Professional,Yes,-461.14,520.00,Soft Drink,14.7
3,TXN000041,2023-01-01,07:13:00,CUST01289,32,Male,Honey,Spreads,4,219.12,...,Yes,Festival,100,4,Young Professional,Yes,-92.52,222.86,Honey,3.3
4,TXN000043,2023-01-01,08:15:00,CUST01077,17,Female,Tea,Beverages,2,29.85,...,Yes,Festival,100,4,Student,No,-0.66,24.00,Biscuit,25.2
5,TXN000044,2023-01-01,08:15:00,CUST01077,17,Female,Jam,Spreads,1,108.70,...,Yes,Festival,100,4,Student,No,-46.44,36.00,Bread,1.9
6,TXN000030,2023-01-01,08:29:00,CUST01555,45,Other,Rusk,Biscuits & Cookies,3,33.98,...,Yes,Festival,97,4,Family,No,2.16,23.14,Rusk,22.8
7,TXN000031,2023-01-01,08:43:00,CUST01329,30,Female,Chocolate Cake,Cakes,1,416.93,...,Yes,Festival,88,4,Young Professional,Yes,-84.16,34.29,Soft Drink,0.8
8,TXN000032,2023-01-01,08:43:00,CUST01329,30,Female,Jam,Spreads,2,112.70,...,Yes,Festival,88,4,Young Professional,Yes,-96.44,72.00,Bread,9.0
9,TXN000033,2023-01-01,08:43:00,CUST01329,30,Female,Bread,Bakery Staples,1,40.55,...,Yes,Festival,88,4,Young Professional,Yes,-16.59,22.00,Milk,9.5
10,TXN000034,2023-01-01,08:43:00,CUST01329,30,Female,Honey,Spreads,2,219.03,...,Yes,Festival,88,4,Young Professional,Yes,-111.23,111.43,Honey,9.9
11,TXN000024,2023-01-01,08:55:00,CUST00414,46,Male,Honey,Spreads,1,224.76,...,Yes,Festival,100,2,Family,No,-53.55,55.71,Honey,3.7
12,TXN000025,2023-01-01,08:55:00,CUST00414,46,Male,Peanut Butter,Spreads,3,175.06,...,Yes,Festival,100,2,Family,No,-218.49,128.57,Bread,1.7
13,TXN000026,2023-01-01,08:55:00,CUST00414,46,Male,Milk,Dairy,2,30.63,...,Yes,Festival,100,2,Family,No,-28.71,13.33,Bread,14.2
14,TXN000018,2023-01-01,10:05:00,CUST01201,30,Female,Tea Cake,Cakes,2,146.60,...,No,NaN,68,2,Young Professional,Yes,20.78,97.14,Tea Cake,29.2
15,TXN000019,2023-01-01,10:05:00,CUST01201,30,Female,Paneer,Dairy,3,78.13,...,No,NaN,68,2,Young Professional,Yes,-88.58,123.75,Paneer,19.1
16,TXN000020,2023-01-01,10:05:00,CUST01201,30,Female,Chocolate Cake,Cakes,2,421.13,...,No,NaN,68,2,Young Professional,Yes,276.85,68.57,Soft Drink,9.9
17,TXN000021,2023-01-01,10:05:00,CUST01201,30,Female,Cupcake,Cupcakes,4,34.55,...,No,NaN,68,2,Young Professional,Yes,-40.10,90.00,Cupcake,33.2
18,TXN000047,2023-01-01,10:05:00,CUST00193,34,Male,Jam,Spreads,2,107.07,...,No,NaN,78,4,Family,Yes,-20.68,72.00,Bread,6.5
19,TXN000014,2023-01-01,10:06:00,CUST01471,18,Female,Coffee,Beverages,6,49.02,...,Yes,Festival,84,3,Student,Yes,6.82,24.00,Muffin,10.4

In [22]:
df.shape

(16569, 41)

In [23]:
df.Category.unique()

<ArrowStringArray>
['Biscuits & Cookies',            'Spreads',              'Cakes',
          'Beverages',     'Bakery Staples',              'Dairy',
           'Cupcakes',     'Savoury Snacks',            'Muffins',
      'Bakery Snacks']
Length: 10, dtype: str

In [24]:
transactions = df.groupby(['Customer_ID', 'Date', 'Time'])['Category'].apply(lambda x : list(set(x))).tolist()

for i,j in transactions:
    print(i)
    print("*"*100)
    print(j)
    break

transactions

Cupcakes
****************************************************************************************************
Biscuits & Cookies

[['Cupcakes', 'Biscuits & Cookies'],
 ['Beverages'],
 ['Savoury Snacks', 'Beverages'],
 ['Bakery Staples'],
 ['Cupcakes', 'Cakes'],
 ['Cakes'],
 ['Savoury Snacks', 'Beverages'],
 ['Cupcakes', 'Beverages'],
 ['Beverages', 'Bakery Snacks', 'Biscuits & Cookies'],
 ['Dairy'],
 ['Biscuits & Cookies', 'Bakery Staples'],
 ['Savoury Snacks'],
 ['Cakes', 'Bakery Snacks'],
 ['Cupcakes'],
 ['Dairy'],
 ['Dairy', 'Muffins'],
 ['Dairy', 'Muffins', 'Beverages'],
 ['Beverages'],
 ['Beverages', 'Biscuits & Cookies'],
 ['Spreads', 'Beverages'],
 ['Bakery Snacks', 'Beverages'],
 ['Muffins'],
 ['Bakery Staples'],
 ['Cakes', 'Bakery Snacks'],
 ['Cakes'],
 ['Beverages'],
 ['Cakes', 'Dairy'],
 ['Spreads', 'Savoury Snacks'],
 ['Cakes'],
 ['Cupcakes'],
 ['Dairy'],
 ['Bakery Staples'],
 ['Savoury Snacks'],
 ['Savoury Snacks', 'Beverages'],
 ['Savoury Snacks'],
 ['Cupcakes', 'Cakes'],
 ['Dairy'],
 ['Bakery Snacks', 'Muffins'],
 ['Cakes'],
 ['Dairy'],
 ['Bakery Staples'],
 ['Cakes'],
 ['Dairy'],
 ['Spreads', 'Cakes', 'Muffins'],
 ['Spreads'],
 ['Beverages'],
 ['Savoury Snacks', 'Cakes', 'Beverages'],
 ['Savoury Snacks', 'Beverages'],
 ['Savoury Snacks', 'Dairy'],
 ['Dairy'],
 ['Bakery Staples'],
 ['Beverages', 'Bakery Staples'],
 ['Bakery Staples'],
 ['Spreads', 'Bakery Staples'],
 ['Biscuits & Cookies'],
 ['Spreads'],
 ['Savoury Snacks'],
 ['Bakery Snacks', 'Beverages', 'Biscuits & Cookies'],
 ['Dairy', 'Beverages', 'Biscuits & Cookies'],
 ['Dairy', 'Biscuits & Cookies'],
 ['Beverages', 'Biscuits & Cookies'],
 ['Cupcakes', 'Bakery Staples'],
 ['Spreads', 'Bakery Staples'],
 ['Spreads', 'Cakes', 'Dairy'],
 ['Savoury Snacks', 'Beverages'],
 ['Dairy', 'Bakery Staples'],
 ['Spreads', 'Beverages', 'Bakery Staples'],
 ['Bakery Staples'],
 ['Cakes', 'Bakery Snacks', 'Bakery Staples'],
 ['Cakes'],
 ['Biscuits & Cookies', 'Bakery Staples'],
 ['Spreads', 'Beverages'],
 ['Bakery Staples'],
 ['Dairy'],
 ['Spreads'],
 ['Cakes'],
 ['Spreads', 'Dairy', 'Cakes'],
 ['Cupcakes', 'Beverages'],
 ['Savoury Snacks', 'Beverages'],
 ['Bakery Snacks', 'Biscuits & Cookies'],
 ['Dairy', 'Bakery Staples'],
 ['Cakes'],
 ['Savoury Snacks', 'Biscuits & Cookies'],
 ['Cakes'],
 ['Beverages'],
 ['Bakery Staples'],
 ['Cupcakes'],
 ['Cakes', 'Bakery Snacks', 'Beverages'],
 ['Cupcakes'],
 ['Cupcakes', 'Muffins'],
 ['Cakes', 'Muffins'],
 ['Savoury Snacks', 'Bakery Snacks', 'Beverages'],
 ['Savoury Snacks', 'Dairy'],
 ['Savoury Snacks', 'Biscuits & Cookies'],
 ['Cupcakes'],
 ['Beverages', 'Dairy', 'Biscuits & Cookies'],
 ['Dairy'],
 ['Beverages'],
 ['Dairy'],
 ['Cakes', 'Bakery Staples'],
 ['Muffins'],
 ['Savoury Snacks'],
 ['Cakes'],
 ['Cupcakes', 'Bakery Snacks', 'Beverages'],
 ['Spreads'],
 ['Bakery Staples'],
 ['Beverages'],
 ['Dairy'],
 ['Dairy'],
 ['Cakes', 'Bakery Staples'],
 ['Beverages', 'Biscuits & Cookies'],
 ['Cupcakes'],
 ['Spreads'],
 ['Biscuits & Cookies'],
 ['Cupcakes', 'Savoury Snacks', 'Cakes'],
 ['Cakes', 'Bakery Snacks', 'Beverages', 'Bakery Staples'],
 ['Beverages'],
 ['Cakes', 'Dairy'],
 ['Beverages', 'Biscuits & Cookies'],
 ['Savoury Snacks', 'Beverages'],
 ['Beverages'],
 ['Cakes', 'Beverages'],
 ['Spreads', 'Dairy'],
 ['Cakes', 'Bakery Staples'],
 ['Spreads'],
 ['Beverages'],
 ['Spreads', 'Biscuits & Cookies'],
 ['Cakes', 'Muffins'],
 ['Bakery Snacks'],
 ['Dairy'],
 ['Cakes', 'Biscuits & Cookies'],
 ['Cupcakes'],
 ['Dairy'],
 ['Savoury Snacks'],
 ['Cupcakes', 'Savoury Snacks', 'Dairy'],
 ['Dairy'],
 ['Beverages', 'Cakes', 'Muffins'],
 ['Cupcakes', 'Beverages'],
 ['Dairy', 'Cakes', 'Beverages', 'Bakery Staples'],
 ['Cupcakes', 'Dairy', 'Bakery Snacks'],
 ['Bakery Snacks'],
 ['Cupcakes', 'Savoury Snacks'],
 ['Spreads', 'Cakes'],
 ['Dairy', 'Bakery Snacks'],
 ['Spreads'],
 ['Dairy'],
 ['Dairy'],
 ['Cakes', 'Dairy', 'Biscuits & Cookies'],
 ['Dairy'],
 ['Dairy'],
 ['Beverages', 'Bakery Staples'],
 ['Cupcakes'],
 ['Spreads'],
 ['Savoury Snacks'],
 ['Beverages'],
 ['Cakes'],
 ['Dairy', 'Bakery Staples'],
 ['Bakery Staples'],
 ['Savoury Snacks', 'Bakery Staples'],
 ['Cupcakes', 'Cakes'],
 ['Dairy'],
 ['Cupcakes', 'Dairy'],
 ['Cupcakes'],
 ['Dairy'],
 ['Beverages'],
 ['Savoury Snacks', 'Cakes', 'Bakery Snacks'],
 ['Cakes', 'Beverages'],
 ['Savoury Snacks', 'Beverages', 'Bakery Staples'],
 ['Cupcakes', 'Savoury Snacks', 'Cakes', 'Bakery Staples'],
 ['Spreads', 'Cakes', 'Beverages', 'Bakery Staples'],
 ['Cakes', 'Biscuits & Cookies'],
 ['Savoury Snacks', 'Beverages'],
 ['Cakes', 'Bakery Staples'],
 ['Bakery Staples'],
 ['Cupcakes'],
 ['Dairy', 'Bakery Staples'],
 ['Spreads', 'Bakery Staples'],
 ['Cupcakes', 'Cakes'],
 ['Savoury Snacks', 'Cakes', 'Bakery Staples'],
 ['Dairy', 'Bakery Snacks', 'Biscuits & Cookies'],
 ['Dairy', 'Beverages'],
 ['Dairy'],
 ['Savoury Snacks'],
 ['Spreads', 'Dairy'],
 ['Beverages'],
 ['Savoury Snacks'],
 ['Cupcakes', 'Dairy', 'Beverages'],
 ['Cakes'],
 ['Dairy'],
 ['Savoury Snacks', 'Beverages'],
 ['Bakery Snacks'],
 ['Muffins'],
 ['Beverages'],
 ['Cakes'],
 ['Savoury Snacks', 'Biscuits & Cookies'],
 ['Beverages'],
 ['Savoury Snacks', 'Beverages'],
 ['Biscuits & Cookies', 'Bakery Staples'],
 ['Beverages', 'Biscuits & Cookies'],
 ['Bakery Staples'],
 ['Cakes'],
 ['Savoury Snacks', 'Beverages'],
 ['Dairy', 'Muffins'],
 ['Savoury Snacks', 'Biscuits & Cookies'],
 ['Beverages'],
 ['Spreads', 'Cupcakes', 'Cakes', 'Bakery Staples'],
 ['Bakery Staples'],
 ['Cupcakes', 'Beverages'],
 ['Cakes', 'Muffins'],
 ['Spreads', 'Savoury Snacks', 'Bakery Staples'],
 ['Biscuits & Cookies'],
 ['Cakes'],
 ['Spreads', 'Muffins', 'Bakery Staples'],
 ['Beverages'],
 ['Dairy'],
 ['Cakes', 'Beverages'],
 ['Savoury Snacks'],
 ['Dairy'],
 ['Savoury Snacks', 'Dairy', 'Bakery Staples'],
 ['Biscuits & Cookies'],
 ['Cakes', 'Dairy'],
 ['Bakery Snacks', 'Cakes', 'Dairy', 'Beverages'],
 ['Cakes', 'Bakery Snacks'],
 ['Bakery Snacks', 'Biscuits & Cookies'],
 ['Spreads'],
 ['Beverages'],
 ['Dairy'],
 ['Cakes', 'Beverages'],
 ['Cupcakes', 'Dairy', 'Bakery Staples'],
 ['Beverages'],
 ['Beverages'],
 ['Cupcakes'],
 ['Spreads'],
 ['Dairy'],
 ['Spreads', 'Cakes', 'Beverages'],
 ['Beverages', 'Biscuits & Cookies'],
 ['Dairy', 'Bakery Snacks', 'Biscuits & Cookies', 'Bakery Staples'],
 ['Bakery Snacks'],
 ['Dairy'],
 ['Beverages', 'Biscuits & Cookies'],
 ['Bakery Staples'],
 ['Cupcakes'],
 ['Spreads'],
 ['Biscuits & Cookies'],
 ['Savoury Snacks', 'Bakery Staples'],
 ['Biscuits & Cookies'],
 ['Savoury Snacks', 'Biscuits & Cookies'],
 ['Biscuits & Cookies'],
 ['Spreads', 'Bakery Staples'],
 ['Cupcakes'],
 ['Cakes'],
 ['Cakes'],
 ['Bakery Snacks'],
 ['Bakery Staples'],
 ['Spreads'],
 ['Cakes', 'Dairy', 'Beverages'],
 ['Spreads', 'Bakery Staples'],
 ['Dairy', 'Bakery Snacks', 'Cakes'],
 ['Dairy', 'Beverages'],
 ['Biscuits & Cookies', 'Bakery Staples'],
 ['Beverages'],
 ['Beverages'],
 ['Beverages'],
 ['Biscuits & Cookies'],
 ['Spreads', 'Bakery Staples'],
 ['Savoury Snacks'],
 ['Bakery Staples'],
 ['Cakes', 'Bakery Snacks'],
 ['Dairy', 'Bakery Snacks'],
 ['Spreads', 'Bakery Staples'],
 ['Savoury Snacks', 'Beverages'],
 ['Savoury Snacks'],
 ['Savoury Snacks'],
 ['Cupcakes', 'Savoury Snacks'],
 ['Spreads', 'Dairy', 'Muffins'],
 ['Dairy', 'Bakery Staples'],
 ['Dairy', 'Beverages', 'Biscuits & Cookies'],
 ['Beverages', 'Biscuits & Cookies'],
 ['Savoury Snacks', 'Dairy', 'Bakery Snacks', 'Beverages'],
 ['Cupcakes', 'Cakes', 'Beverages'],
 ['Beverages', 'Cakes', 'Biscuits & Cookies'],
 ['Savoury Snacks', 'Beverages'],
 ['Beverages', 'Cakes', 'Biscuits & Cookies'],
 ['Cakes', 'Bakery Snacks', 'Bakery Staples'],
 ['Cakes', 'Beverages'],
 ['Cupcakes', 'Bakery Snacks', 'Beverages'],
 ['Bakery Snacks', 'Beverages'],
 ['Dairy', 'Bakery Staples'],
 ['Bakery Snacks'],
 ['Bakery Staples'],
 ['Beverages', 'Biscuits & Cookies'],
 ['Cupcakes', 'Savoury Snacks', 'Bakery Snacks'],
 ['Dairy'],
 ['Savoury Snacks'],
 ['Biscuits & Cookies'],
 ['Savoury Snacks'],
 ['Spreads'],
 ['Dairy', 'Bakery Staples'],
 ['Cakes', 'Biscuits & Cookies'],
 ['Cakes', 'Bakery Staples'],
 ['Beverages', 'Dairy', 'Biscuits & Cookies'],
 ['Bakery Snacks'],
 ['Cakes'],
 ['Spreads'],
 ['Cakes', 'Biscuits & Cookies'],
 ['Cupcakes', 'Bakery Staples'],
 ['Cakes', 'Bakery Snacks', 'Beverages'],
 ['Cakes', 'Beverages'],
 ['Dairy', 'Bakery Staples'],
 ['Savoury Snacks', 'Bakery Staples'],
 ['Cupcakes', 'Dairy', 'Bakery Staples'],
 ['Cupcakes'],
 ['Beverages', 'Bakery Staples'],
 ['Dairy', 'Biscuits & Cookies'],
 ['Cakes', 'Beverages'],
 ['Cakes', 'Bakery Staples'],
 ['Dairy', 'Bakery Snacks'],
 ['Savoury Snacks'],
 ['Spreads', 'Beverages'],
 ['Cupcakes', 'Beverages', 'Bakery Staples'],
 ['Biscuits & Cookies'],
 ['Bakery Staples'],
 ['Cakes'],
 ['Beverages'],
 ['Savoury Snacks', 'Cakes'],
 ['Cakes', 'Bakery Staples'],
 ['Beverages'],
 ['Spreads', 'Bakery Staples'],
 ['Dairy'],
 ['Spreads'],
 ['Cakes'],
 ['Dairy', 'Bakery Staples'],
 ['Beverages'],
 ['Cakes', 'Beverages'],
 ['Cupcakes'],
 ['Savoury Snacks'],
 ['Cakes'],
 ['Cupcakes', 'Cakes'],
 ['Cupcakes', 'Spreads'],
 ['Muffins'],
 ['Beverages'],
 ['Spreads'],
 ['Dairy'],
 ['Savoury Snacks'],
 ['Spreads', 'Dairy', 'Biscuits & Cookies'],
 ['Biscuits & Cookies'],
 ['Cupcakes'],
 ['Savoury Snacks', 'Beverages'],
 ['Cakes', 'Beverages'],
 ['Cakes'],
 ['Dairy', 'Cakes', 'Beverages'],
 ['Beverages'],
 ['Spreads', 'Cupcakes'],
 ['Spreads', 'Cakes', 'Bakery Staples'],
 ['Spreads', 'Savoury Snacks', 'Beverages'],
 ['Cupcakes', 'Dairy', 'Cakes'],
 ['Biscuits & Cookies'],
 ['Cupcakes'],
 ['Cakes'],
 ['Muffins'],
 ['Bakery Staples'],
 ['Biscuits & Cookies'],
 ['Cupcakes', 'Bakery Snacks', 'Beverages'],
 ['Dairy'],
 ['Muffins'],
 ['Biscuits & Cookies'],
 ['Spreads'],
 ['Biscuits & Cookies'],
 ['Bakery Snacks', 'Beverages'],
 ['Cakes', 'Beverages'],
 ['Dairy'],
 ['Beverages', 'Biscuits & Cookies'],
 ['Cupcakes'],
 ['Cakes'],
 ['Cupcakes', 'Bakery Snacks'],
 ['Savoury Snacks'],
 ['Cupcakes', 'Dairy', 'Spreads'],
 ['Cupcakes'],
 ['Savoury Snacks', 'Beverages', 'Biscuits & Cookies'],
 ['Beverages'],
 ['Biscuits & Cookies'],
 ['Savoury Snacks', 'Beverages'],
 ['Dairy'],
 ['Savoury Snacks', 'Beverages'],
 ['Cakes', 'Beverages', 'Bakery Staples'],
 ['Dairy', 'Bakery Staples'],
 ['Cakes', 'Dairy'],
 ['Savoury Snacks', 'Bakery Snacks', 'Beverages'],
 ['Spreads', 'Cupcakes'],
 ['Biscuits & Cookies'],
 ['Bakery Snacks'],
 ['Bakery Snacks', 'Beverages'],
 ['Cakes', 'Muffins', 'Beverages'],
 ['Cakes', 'Bakery Snacks'],
 ['Beverages'],
 ['Dairy'],
 ['Dairy', 'Biscuits & Cookies'],
 ['Savoury Snacks'],
 ['Cupcakes', 'Beverages'],
 ['Beverages', 'Muffins', 'Cupcakes'],
 ['Bakery Snacks', 'Beverages'],
 ['Spreads', 'Beverages'],
 ['Dairy'],
 ['Cakes', 'Beverages'],
 ['Savoury Snacks'],
 ['Cupcakes', 'Dairy'],
 ['Cupcakes'],
 ['Bakery Snacks', 'Beverages', 'Bakery Staples'],
 ['Savoury Snacks'],
 ['Cupcakes', 'Cakes', 'Spreads'],
 ['Dairy', 'Bakery Staples'],
 ['Dairy'],
 ['Savoury Snacks'],
 ['Beverages'],
 ['Cakes'],
 ['Cupcakes', 'Savoury Snacks', 'Spreads'],
 ['Beverages', 'Biscuits & Cookies'],
 ['Dairy'],
 ['Dairy'],
 ['Dairy'],
 ['Beverages', 'Muffins'],
 ['Cupcakes'],
 ['Bakery Snacks'],
 ['Savoury Snacks', 'Biscuits & Cookies'],
 ['Cupcakes'],
 ['Dairy'],
 ['Cakes', 'Beverages'],
 ['Cakes', 'Bakery Staples'],
 ['Savoury Snacks'],
 ['Cupcakes'],
 ['Beverages'],
 ['Cupcakes', 'Dairy', 'Spreads', 'Biscuits & Cookies'],
 ['Bakery Snacks', 'Muffins'],
 ['Cupcakes', 'Dairy', 'Beverages'],
 ['Beverages', 'Biscuits & Cookies'],
 ['Cupcakes'],
 ['Spreads', 'Cupcakes', 'Cakes', 'Bakery Staples'],
 ['Bakery Snacks'],
 ['Dairy', 'Bakery Staples'],
 ['Spreads', 'Cupcakes'],
 ['Beverages'],
 ['Savoury Snacks'],
 ['Muffins'],
 ['Savoury Snacks', 'Beverages'],
 ['Savoury Snacks'],
 ['Biscuits & Cookies'],
 ['Dairy', 'Beverages'],
 ['Cupcakes', 'Dairy'],
 ['Cakes', 'Beverages', 'Bakery Staples'],
 ['Cakes'],
 ['Bakery Snacks'],
 ['Beverages', 'Muffins', 'Cupcakes'],
 ['Biscuits & Cookies', 'Bakery Staples'],
 ['Cupcakes', 'Dairy'],
 ['Bakery Staples'],
 ['Spreads'],
 ['Savoury Snacks'],
 ['Bakery Staples'],
 ['Cupcakes', 'Dairy'],
 ['Dairy', 'Biscuits & Cookies'],
 ['Dairy', 'Beverages'],
 ['Beverages', 'Biscuits & Cookies'],
 ['Dairy'],
 ['Cakes', 'Bakery Snacks', 'Bakery Staples'],
 ['Dairy', 'Beverages', 'Bakery Staples'],
 ['Dairy', 'Bakery Staples'],
 ['Savoury Snacks', 'Bakery Staples'],
 ['Savoury Snacks', 'Cakes'],
 ['Spreads', 'Beverages'],
 ['Dairy'],
 ['Bakery Snacks', 'Cakes', 'Dairy'],
 ['Muffins'],
 ['Spreads', 'Bakery Snacks'],
 ['Dairy', 'Biscuits & Cookies'],
 ['Bakery Staples'],
 ['Beverages', 'Biscuits & Cookies'],
 ['Dairy', 'Beverages'],
 ['Spreads', 'Bakery Snacks'],
 ['Biscuits & Cookies'],
 ['Cupcakes', 'Muffins'],
 ['Muffins'],
 ['Bakery Staples'],
 ['Beverages'],
 ['Cupcakes'],
 ['Cakes', 'Beverages'],
 ['Beverages'],
 ['Cupcakes'],
 ['Cakes'],
 ['Bakery Snacks'],
 ['Bakery Snacks'],
 ['Savoury Snacks'],
 ['Dairy', 'Bakery Staples'],
 ['Savoury Snacks', 'Bakery Snacks'],
 ['Spreads', 'Savoury Snacks', 'Cakes'],
 ['Cupcakes'],
 ['Cupcakes', 'Bakery Snacks'],
 ['Savoury Snacks'],
 ['Cupcakes'],
 ['Savoury Snacks'],
 ['Dairy', 'Bakery Staples'],
 ['Bakery Staples'],
 ['Muffins'],
 ['Savoury Snacks'],
 ['Dairy', 'Cakes', 'Bakery Staples'],
 ['Dairy'],
 ['Beverages', 'Muffins'],
 ['Muffins'],
 ['Beverages'],
 ['Beverages', 'Muffins'],
 ['Cakes', 'Biscuits & Cookies'],
 ['Beverages', 'Muffins'],
 ['Biscuits & Cookies'],
 ['Cupcakes', 'Beverages'],
 ['Savoury Snacks'],
 ['Cakes', 'Beverages'],
 ['Spreads', 'Cakes', 'Dairy'],
 ['Dairy', 'Bakery Staples'],
 ['Muffins'],
 ['Savoury Snacks', 'Dairy', 'Cakes', 'Bakery Staples'],
 ['Savoury Snacks', 'Dairy', 'Muffins'],
 ['Bakery Staples'],
 ['Dairy', 'Beverages'],
 ['Cupcakes', 'Beverages'],
 ['Biscuits & Cookies'],
 ['Cupcakes'],
 ['Biscuits & Cookies'],
 ['Beverages', 'Cakes', 'Biscuits & Cookies'],
 ['Dairy', 'Cakes', 'Beverages'],
 ['Cupcakes'],
 ['Dairy'],
 ['Cupcakes', 'Savoury Snacks', 'Cakes', 'Biscuits & Cookies'],
 ['Cakes'],
 ['Bakery Snacks', 'Beverages', 'Bakery Staples'],
 ['Spreads', 'Bakery Staples'],
 ['Cupcakes', 'Dairy', 'Bakery Staples'],
 ['Dairy', 'Bakery Staples'],
 ['Beverages'],
 ['Savoury Snacks'],
 ['Savoury Snacks', 'Dairy'],
 ['Savoury Snacks'],
 ['Savoury Snacks', 'Dairy'],
 ['Beverages'],
 ['Spreads'],
 ['Dairy', 'Beverages'],
 ['Bakery Snacks'],
 ['Beverages', 'Biscuits & Cookies'],
 ['Cupcakes', 'Biscuits & Cookies', 'Bakery Staples'],
 ['Biscuits & Cookies'],
 ['Beverages', 'Muffins'],
 ['Savoury Snacks', 'Dairy', 'Beverages', 'Bakery Staples'],
 ['Bakery Snacks'],
 ['Dairy', 'Bakery Staples'],
 ['Beverages'],
 ['Cupcakes', 'Bakery Snacks'],
 ['Muffins'],
 ['Biscuits & Cookies'],
 ['Dairy'],
 ['Spreads', 'Bakery Staples'],
 ['Bakery Snacks'],
 ['Cakes'],
 ['Bakery Snacks', 'Beverages'],
 ['Biscuits & Cookies'],
 ['Savoury Snacks', 'Bakery Staples'],
 ['Savoury Snacks'],
 ['Cakes', 'Bakery Snacks', 'Beverages'],
 ['Cakes', 'Beverages', 'Biscuits & Cookies'],
 ['Bakery Snacks', 'Biscuits & Cookies'],
 ['Dairy', 'Beverages'],
 ['Cakes', 'Biscuits & Cookies'],
 ['Beverages'],
 ['Savoury Snacks'],
 ['Beverages'],
 ['Beverages', 'Biscuits & Cookies'],
 ['Cupcakes'],
 ['Beverages'],
 ['Dairy', 'Beverages'],
 ['Spreads', 'Bakery Staples'],
 ['Cupcakes', 'Savoury Snacks', 'Beverages'],
 ['Muffins', 'Beverages'],
 ['Cupcakes', 'Savoury Snacks', 'Beverages'],
 ['Beverages', 'Biscuits & Cookies'],
 ['Dairy'],
 ['Dairy', 'Muffins', 'Bakery Staples'],
 ['Cupcakes', 'Cakes', 'Muffins', 'Beverages'],
 ['Bakery Staples'],
 ['Cakes', 'Beverages'],
 ['Spreads', 'Savoury Snacks', 'Bakery Staples'],
 ['Cupcakes', 'Beverages'],
 ['Beverages'],
 ['Dairy', 'Bakery Snacks'],
 ['Savoury Snacks', 'Beverages'],
 ['Bakery Staples'],
 ['Savoury Snacks', 'Beverages'],
 ['Spreads', 'Cakes', 'Bakery Staples'],
 ['Dairy'],
 ['Cakes', 'Beverages'],
 ['Cakes', 'Beverages'],
 ['Savoury Snacks'],
 ['Savoury Snacks'],
 ['Dairy'],
 ['Savoury Snacks'],
 ['Beverages'],
 ['Spreads', 'Savoury Snacks', 'Cakes'],
 ['Spreads'],
 ['Cakes', 'Beverages'],
 ['Cakes', 'Muffins', 'Beverages'],
 ['Biscuits & Cookies'],
 ['Muffins'],
 ['Dairy'],
 ['Beverages'],
 ['Cupcakes'],
 ['Spreads', 'Cakes'],
 ['Cakes', 'Beverages'],
 ['Beverages', 'Biscuits & Cookies'],
 ['Bakery Snacks'],
 ['Cupcakes', 'Cakes', 'Muffins'],
 ['Cakes'],
 ['Beverages'],
 ['Cakes'],
 ['Cakes'],
 ['Spreads', 'Bakery Snacks'],
 ['Cupcakes', 'Cakes'],
 ['Savoury Snacks', 'Beverages'],
 ['Cupcakes'],
 ['Beverages'],
 ['Cupcakes', 'Biscuits & Cookies', 'Bakery Staples'],
 ['Dairy'],
 ['Biscuits & Cookies', 'Bakery Staples'],
 ['Beverages'],
 ['Dairy'],
 ['Savoury Snacks', 'Biscuits & Cookies'],
 ['Cakes'],
 ['Beverages'],
 ['Beverages', 'Savoury Snacks', 'Muffins'],
 ['Cakes'],
 ['Bakery Staples'],
 ['Dairy'],
 ['Spreads', 'Dairy', 'Bakery Staples'],
 ['Cakes', 'Muffins', 'Beverages'],
 ['Muffins', 'Biscuits & Cookies'],
 ['Bakery Staples'],
 ['Bakery Snacks', 'Beverages', 'Biscuits & Cookies'],
 ['Muffins'],
 ['Beverages', 'Spreads', 'Muffins'],
 ['Dairy', 'Bakery Staples'],
 ['Dairy'],
 ['Spreads'],
 ['Beverages', 'Muffins'],
 ['Cakes', 'Bakery Snacks', 'Beverages', 'Bakery Staples'],
 ['Cakes'],
 ['Cakes', 'Beverages'],
 ['Cupcakes', 'Bakery Snacks'],
 ['Biscuits & Cookies'],
 ['Bakery Snacks'],
 ['Cakes'],
 ['Dairy'],
 ['Spreads'],
 ['Savoury Snacks'],
 ['Dairy'],
 ['Dairy'],
 ['Beverages'],
 ['Spreads', 'Bakery Staples'],
 ['Cakes', 'Beverages'],
 ['Bakery Staples'],
 ['Cupcakes'],
 ['Savoury Snacks', 'Dairy', 'Muffins'],
 ['Cakes', 'Bakery Snacks', 'Beverages'],
 ['Cakes', 'Beverages'],
 ['Cakes', 'Bakery Staples'],
 ['Cupcakes'],
 ['Cakes', 'Beverages'],
 ['Dairy'],
 ['Cupcakes', 'Dairy', 'Muffins'],
 ['Spreads', 'Cakes', 'Muffins', 'Cupcakes'],
 ['Cupcakes', 'Beverages'],
 ['Bakery Staples'],
 ['Bakery Staples'],
 ['Cakes', 'Beverages'],
 ['Biscuits & Cookies'],
 ['Savoury Snacks', 'Beverages'],
 ['Cupcakes', 'Muffins', 'Biscuits & Cookies'],
 ['Muffins'],
 ['Cakes', 'Beverages'],
 ['Cupcakes', 'Cakes', 'Muffins', 'Beverages'],
 ['Beverages'],
 ['Savoury Snacks', 'Cakes'],
 ['Bakery Snacks', 'Biscuits & Cookies', 'Bakery Staples'],
 ['Bakery Staples'],
 ['Dairy', 'Bakery Snacks', 'Beverages'],
 ['Bakery Staples'],
 ['Dairy'],
 ['Beverages'],
 ['Spreads'],
 ['Spreads', 'Bakery Staples'],
 ['Cakes'],
 ['Spreads'],
 ['Savoury Snacks', 'Muffins', 'Biscuits & Cookies'],
 ['Dairy'],
 ['Savoury Snacks', 'Dairy'],
 ['Cupcakes', 'Savoury Snacks', 'Spreads'],
 ['Savoury Snacks', 'Cakes', 'Beverages'],
 ['Dairy', 'Bakery Staples'],
 ['Cupcakes', 'Beverages', 'Bakery Staples'],
 ['Beverages'],
 ['Bakery Staples'],
 ['Bakery Snacks'],
 ['Muffins'],
 ['Bakery Snacks'],
 ['Cakes', 'Bakery Snacks'],
 ['Dairy'],
 ['Dairy'],
 ['Cupcakes', 'Savoury Snacks'],
 ['Dairy', 'Biscuits & Cookies'],
 ['Cakes'],
 ['Spreads'],
 ['Dairy', 'Beverages'],
 ['Savoury Snacks', 'Beverages'],
 ['Bakery Snacks', 'Beverages'],
 ['Spreads', 'Bakery Staples'],
 ['Biscuits & Cookies', 'Bakery Staples'],
 ['Dairy', 'Bakery Staples'],
 ['Savoury Snacks'],
 ['Spreads'],
 ['Cupcakes'],
 ['Spreads', 'Biscuits & Cookies'],
 ['Dairy', 'Muffins', 'Bakery Staples'],
 ['Beverages'],
 ['Cupcakes', 'Beverages'],
 ['Cupcakes'],
 ['Savoury Snacks'],
 ['Cupcakes', 'Spreads'],
 ['Spreads', 'Cakes', 'Beverages', 'Bakery Staples'],
 ['Spreads', 'Bakery Staples'],
 ['Beverages'],
 ['Dairy', 'Cakes', 'Bakery Staples'],
 ['Beverages'],
 ['Dairy', 'Bakery Staples'],
 ['Beverages', 'Biscuits & Cookies'],
 ['Beverages', 'Biscuits & Cookies'],
 ['Dairy', 'Bakery Snacks', 'Beverages'],
 ['Cupcakes', 'Cakes', 'Biscuits & Cookies'],
 ['Dairy'],
 ['Savoury Snacks', 'Beverages'],
 ['Savoury Snacks', 'Biscuits & Cookies'],
 ['Savoury Snacks'],
 ['Beverages'],
 ['Savoury Snacks'],
 ['Spreads'],
 ['Cupcakes', 'Bakery Snacks'],
 ['Cakes', 'Dairy'],
 ['Cakes'],
 ['Beverages', 'Biscuits & Cookies'],
 ['Beverages'],
 ['Cupcakes', 'Biscuits & Cookies'],
 ['Cupcakes', 'Savoury Snacks', 'Dairy', 'Bakery Staples'],
 ['Savoury Snacks'],
 ['Beverages'],
 ['Beverages'],
 ['Dairy'],
 ['Muffins'],
 ['Biscuits & Cookies'],
 ['Cupcakes', 'Cakes', 'Beverages', 'Bakery Staples'],

In [25]:
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori, association_rules

# Step 1: Customer + Date + Time ke basis par Category ki list banayein

# Step 2: TransactionEncoder chalayein
te = TransactionEncoder()
te_ary = te.fit(transactions).transform(transactions)
df_encoded = pd.DataFrame(te_ary, columns=te.columns_)

# Step 3: Frequent itemsets nikalein
frequent_itemsets = apriori(df_encoded, min_support=0.01, use_colnames=True)

# Step 4: Association rules generate karein
rules = association_rules(frequent_itemsets, metric="lift", min_threshold=1.0)
rules[['antecedents', 'consequents', 'support', 'confidence', 'lift']].sort_values('lift', ascending=False)

,antecedents,consequents,support,confidence,lift
5,frozenset({Bakery Staples}),frozenset({Spreads}),0.045137,0.222882,1.672985
4,frozenset({Spreads}),frozenset({Bakery Staples}),0.045137,0.338802,1.672985
2,frozenset({Dairy}),frozenset({Bakery Staples}),0.062951,0.250435,1.236632
3,frozenset({Bakery Staples}),frozenset({Dairy}),0.062951,0.310847,1.236632
9,frozenset({Muffins}),frozenset({Beverages}),0.027541,0.342391,1.126125
8,frozenset({Beverages}),frozenset({Muffins}),0.027541,0.090582,1.126125
1,frozenset({Beverages}),frozenset({Bakery Snacks}),0.033333,0.109633,1.118334
0,frozenset({Bakery Snacks}),frozenset({Beverages}),0.033333,0.340022,1.118334
10,frozenset({Savoury Snacks}),frozenset({Beverages}),0.059235,0.329083,1.082355
11,frozenset({Beverages}),frozenset({Savoury Snacks}),0.059235,0.194824,1.082355
7,frozenset({Beverages}),frozenset({Cakes}),0.058798,0.193386,1.002540
6,frozenset({Cakes}),frozenset({Beverages}),0.058798,0.304816,1.002540

In [26]:
df.isnull().sum()

Transaction_ID              0
Date                        0
Time                        0
Customer_ID                 0
Customer_Age                0
Customer_Gender             0
Product                     0
Category                    0
Quantity                    0
Unit_Price                  0
Discount_Percentage         0
Discount_Amount             0
Selling_Price               0
Total_Bill                  0
Payment_Method              0
Weather                     0
Temperature                 0
Season                      0
Day_of_Week                 0
Weekend                     0
Festival                15960
Store_ID                    0
Employee_ID                 0
Shelf_Life_Days             0
Manufacturing_Date          0
Expiry_Date                 0
Stock_Available             0
Units_Produced              0
Units_Sold                  0
Unsold_Units                0
Expiry_Risk                 0
Promotion_Applied           0
Promotion_Type          13209
Promotion_Score             0
Customer_Rating             0
Customer_Segment            0
Loyalty_Member              0
Profit                      0
Waste_Cost                  0
Recommended_Product         0
Recommended_Discount        0
dtype: int64

In [27]:
# 1. Group unique categories per (Customer_ID, Date, Time) using a dictionary
transaction_dict = {}

for _, row in df.iterrows():
    key = (row["Customer_ID"], row["Date"], row["Time"])
    category = row["Category"]

    if key not in transaction_dict:
        transaction_dict[key] = set()

    transaction_dict[key].add(category)

# 2. Convert the dictionary values into a list of lists
transactions = [list(categories) for categories in transaction_dict.values()]

In [28]:
transactions_dict = {}

for row in df[['Customer_ID', 'Date', 'Time', 'Category']].itertuples(index=False):
    key = (row.Customer_ID, row.Date, row.Time)
    transactions_dict.setdefault(key, set()).add(row.Category)

transactions = list(transactions_dict.values())
transactions = [list(items) for items in transactions]

In [29]:
transactions = df.groupby(['Customer_ID', 'Date', 'Time'])['Category'].apply(lambda x : list(set(x)))
transactions

Customer_ID  Date        Time
CUST00001    2023-03-10  18:00:00        [Cupcakes, Biscuits & Cookies]
             2023-05-12  10:42:00                           [Beverages]
             2023-09-26  10:53:00           [Savoury Snacks, Beverages]
             2023-12-02  09:35:00                      [Bakery Staples]
             2023-12-09  16:16:00                     [Cupcakes, Cakes]
                                                    ...
CUST02200    2023-08-18  13:50:00                      [Bakery Staples]
             2023-11-05  11:20:00    [Savoury Snacks, Cakes, Beverages]
             2024-05-12  18:13:00           [Savoury Snacks, Beverages]
             2024-06-15  10:50:00                           [Beverages]
             2024-09-02  16:45:00      [Spreads, Savoury Snacks, Dairy]
Name: Category, Length: 9150, dtype: object

In [33]:
transaction_df = pd.DataFrame(transactions)
transaction_df.head(10)

                                                                       Category
Customer_ID Date       Time
CUST00001   2023-03-10 18:00:00                  [Cupcakes, Biscuits & Cookies]
            2023-05-12 10:42:00                                     [Beverages]
            2023-09-26 10:53:00                     [Savoury Snacks, Beverages]
            2023-12-02 09:35:00                                [Bakery Staples]
            2023-12-09 16:16:00                               [Cupcakes, Cakes]
            2024-09-19 12:34:00                                         [Cakes]
            2024-10-01 08:18:00                     [Savoury Snacks, Beverages]
CUST00002   2024-04-14 18:47:00                           [Cupcakes, Beverages]
            2024-07-21 15:09:00  [Beverages, Bakery Snacks, Biscuits & Cookies]
            2024-10-13 19:29:00                                         [Dairy]